fix workflow

diff --git a/.github/workflows/i14y-ui-release-deploy.yml b/.github/workflows/i14y-ui-release-deploy.yml
--- a/.github/workflows/i14y-ui-release-deploy.yml
+++ b/.github/workflows/i14y-ui-release-deploy.yml
@@ -127,21 +127,22 @@ jobs:
         run: |
           echo "🚀 Starting Azure Static Web App deployment..."
           set -e  # stop script on any unhandled error
-          cp staticwebapp.config.json dist/BFS-IOP-ADMIN-UI/;
+          cp staticwebapp.config.json dist/BFS-IOP-ADMIN-UI/browser/;
 
           # Deploy and capture log
-          swa deploy "dist/BFS-IOP-ADMIN-UI" \
+          swa deploy "dist/BFS-IOP-ADMIN-UI/browser/" \
             --env prod \
             --deployment-token "$AZURE_STATIC_WEB_APPS_API_TOKEN" \
             --verbose > deploy.log 2>&1
             # Check log for "deployed"
-            if grep -q "deployed" deploy.log; then
-              echo "✅ Deployment completed successfully."
-            else
-              echo "❌ Deployment failed. Last 40 lines of log:"
-              tail -n 40 deploy.log
-              exit 1  # mark step as failed
-            fi
+
+          if grep -q "deployed" deploy.log; then
+            echo "✅ Deployment completed successfully."
+          else
+            echo "❌ Deployment failed. Last 40 lines of log:"
+            tail -n 40 deploy.log
+            exit 1
+          fi
         working-directory: src/ui/admin-ui
 
       - name: Upload npm logs artifact
@@ -251,6 +252,27 @@ jobs:
 
       - name: Install Azure Static Web Apps CLI
         run: npm install -g @azure/static-web-apps-cli
+
+
+      - name: Deploy to Azure Static Web App
+        env:
+          AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ADMIN_UI }}
+        run: |
+          echo "Starting Azure Static Web App deployment..."
+          set -e
+
+          swa deploy "dist/BFS-IOP-ADMIN-UI" \
+            --env prod \
+            --deployment-token "$AZURE_STATIC_WEB_APPS_API_TOKEN" \
+            --verbose > deploy.log 2>&1
+
+          if grep -q "deployed" deploy.log; then
+            echo "✅ Deployment completed successfully."
+          else
+            echo "❌ Deployment failed. Last 40 lines of log:"
+            tail -n 40 deploy.log
+            exit 1
+          fi
 
       - name: Deploy to Azure Static Web App
         env:
